Differentiate meshes by color
EMTech-AUTh/ADCSSims.jl pull request #50
Opened 2023-12-26 16:40 UTC by voulgarakisromanos

2023-12-31 12:59 UTC, xlxs4 commented on Project.toml
> -GeoIO = "f5a160d5-e41d-4189-8b61-d57781c419e3"
I'm happy :)
```
  [c9ce4bd3] - ArchGDAL v0.10.2
  [dce04be8] - ArgCheck v2.3.0
  [4c555306] - ArrayLayouts v1.4.5
  [198e06fe] - BangBang v0.3.39
  [9718e550] - Baselet v0.1.1
  [c3b6d118] - BitIntegers v0.3.1
  [179af706] - CFTime v0.1.2
  [324d7699] - CategoricalArrays v0.10.8
  [5ba52731] - CodecLz4 v0.4.1
  [6b39b394] - CodecZstd v0.7.2
  [9cc86067] - ColumnSelectors v0.1.1
  [1fbeeb36] - CommonDataModel v0.2.5
  [75c7ada1] - DBFTables v1.2.4
  [6cb2f572] - DataScienceTraits v0.2.2
  [55939f99] - DecFP v1.3.2
  [244e2a9f] - DefineSingletons v0.1.2
  [3c3547ce] - DiskArrays v0.3.22
  [5207ad80] - FNVHash v0.1.0
  [add2ef01] - GDAL v1.7.0
  [b16dfd50] - GRIB v0.3.0
  [82be9cdb] - GRIBDatasets v0.3.0
  [68eda718] - GeoFormatTypes v0.4.2
  [f5a160d5] - GeoIO v1.12.0
  [0329782f] - GeoInterfaceRecipes v1.0.2
  [61d90e0f] - GeoJSON v0.7.3
  [e99870d8] - GeoParquet v0.2.1
  [e502b557] - GeoTables v1.14.2
  [4610876b] - GslibIO v1.4.6
  [22cec73e] - InitialValues v0.3.1
  [0f8b85d8] - JSON3 v1.14.0
  [5078a376] - LazyArrays v1.8.3
  [a4a7f996] - LightBSON v0.2.17
  [3da0fdf6] - MPIPreferences v0.1.10
  [a3b82374] - MatrixFactorizations v2.1.0
  [128add7d] - MicroCollections v0.1.4
  [85f8d34a] - NCDatasets v0.13.2
  [98572fba] - Parquet2 v0.2.19
  [dc215faf] - ReadVTK v0.2.0
  [8e980c4a] - Shapefile v0.10.0
  [59d4ed8c] - Snappy v0.4.2
  [171d559e] - SplittablesBase v0.1.15
  [856f2bd8] - StructTypes v1.10.0
  [ab02a1b2] - TableOperations v1.2.0
  [9be31aac] - Thrift2 v0.1.4
  [28d57a85] - Transducers v0.4.79
  [c4a57d5a] - UnsafeArrays v1.0.5
  [4004b06d] - VTKBase v1.0.1
  [0f680547] - WellKnownGeometry v0.2.2
  [64499a7a] - WriteVTK v1.18.1
  [8ce61222] - Arrow_jll v10.0.0+1
  [47200ebd] - DecFP_jll v2.0.3+1
  [a7073274] - GDAL_jll v301.800.200+0
  [d604d12d] - GEOS_jll v3.12.0+0
  [0234f1f7] - HDF5_jll v1.14.2+1
  [e33a78d0] - Hwloc_jll v2.10.0+0
  [a51ab1cf] - ICU_jll v69.1.0+0
  [b39eb1a6] - Kerberos_krb5_jll v1.19.3+0
  [08be9ffa] - LibPQ_jll v16.0.0+0
  [d3a379c0] - LittleCMS_jll v2.15.0+0
  [5ced341a] - Lz4_jll v1.9.4+0
  [7cb0a576] - MPICH_jll v4.1.2+1
  [f1f71cc9] - MPItrampoline_jll v5.3.1+1
  [9237b28f] - MicrosoftMPI_jll v10.1.4+1
  [7243133f] - NetCDF_jll v400.902.208+0
  [643b3616] - OpenJpeg_jll v2.5.0+0
  [fe0851c0] - OpenMPI_jll v5.0.1+0
  [32165bc3] - PMIx_jll v4.2.7+0
  [58948b4f] - PROJ_jll v901.300.0+0
  [76ed43ae] - SQLite_jll v3.43.0+0
  [e0b8ae26] - Thrift_jll v0.16.0+0
  [28df3c45] - boost_jll v1.76.0+1
  [b04048ba] - eccodes_jll v2.28.0+0
  [477f73a3] - libaec_jll v1.0.6+1
  [1080aeaf] - libevent_jll v2.1.13+1
  [06c338fa] - libgeotiff_jll v100.701.100+0
  [eb928a42] - prrte_jll v3.0.2+0
  [fe1e1685] - snappy_jll v1.1.9+1
```

2023-12-31 14:04 UTC, xlxs4 requested changes

2023-12-31 14:04 UTC, xlxs4 commented on src/mesh_preprocessing.jl
> +Meshes.viz(mesh::ExtendedMesh) = Meshes.viz(mesh.mesh)
This doesn't seem to work

2023-12-31 14:09 UTC, voulgarakisromanos commented on src/ADCSSims.jl
>  include("power_generation.jl")
power.jl sounds cooler

2023-12-31 14:40 UTC, voulgarakisromanos commented on src/mesh_preprocessing.jl
> +Meshes.viz(mesh::ExtendedMesh) = Meshes.viz(mesh.mesh)
it needs a backend

2023-12-31 14:43 UTC, voulgarakisromanos commented on src/power_generation.jl
> +function calculate_projection(vector, mesh, bvh_root::BVHNode)
done

2023-12-31 14:43 UTC, voulgarakisromanos commented on src/power_generation.jl
> +function PowerGeneration(mesh_path::String; panel_efficiency=0.295)
done

2023-12-31 14:43 UTC, xlxs4 commented on src/mesh_preprocessing.jl
> +Meshes.viz(mesh::ExtendedMesh) = Meshes.viz(mesh.mesh)
I saw the comment in Meshes.jl source. It still doesn't work

2023-12-31 14:43 UTC, voulgarakisromanos commented on src/power_generation.jl
> +function calculate_power(power_struct::PowerGeneration, sun_vector)
done

2023-12-31 14:43 UTC, voulgarakisromanos commented on src/power_generation.jl
> +    mesh = load_meshes(mesh_path)
opted for meshes = load_meshes

2023-12-31 14:43 UTC, voulgarakisromanos commented on src/ADCSSims.jl
> +include("mesh_preprocessing.jl")
done

2023-12-31 14:43 UTC, voulgarakisromanos commented on src/ADCSSims.jl
>  include("power_generation.jl")
done

2023-12-31 14:43 UTC, xlxs4 commented on src/mesh_preprocessing.jl
> +Meshes.viz(mesh::ExtendedMesh) = Meshes.viz(mesh.mesh)
```
julia> ADCSSims.viz(extmesh)
ERROR: No recipe for viz
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] plot!
   @ ~/.julia/packages/Makie/Qvk4f/src/interfaces.jl:227 [inlined]
 [3] connect_plot!(parent::Scene, plot::Plot{Meshes.viz, Tuple{Vector{ADCSSims.ExtendedMesh{…}}}})
   @ Makie ~/.julia/packages/Makie/Qvk4f/src/interfaces.jl:255
 [4] plot!
   @ Makie ~/.julia/packages/Makie/Qvk4f/src/interfaces.jl:260 [inlined]
 [5] plot!(ax::Axis, plot::Plot{Meshes.viz, Tuple{Vector{ADCSSims.ExtendedMesh{Vector{…}, Vector{…}, Vector{…}}}}})
   @ Makie ~/.julia/packages/Makie/Qvk4f/src/figureplotting.jl:291
 [6] plot!(fa::Makie.FigureAxis, plot::Plot{Meshes.viz, Tuple{Vector{ADCSSims.ExtendedMesh{…}}}})
   @ Makie ~/.julia/packages/Makie/Qvk4f/src/figureplotting.jl:288
 [7] _create_plot(F::Function, attributes::Dict{Symbol, Any}, args::Vector{ADCSSims.ExtendedMesh{…}})
   @ Makie ~/.julia/packages/Makie/Qvk4f/src/figureplotting.jl:250
 [8] viz(args::Vector{ADCSSims.ExtendedMesh{Vector{Meshes.Triangle{3, Float64}}, Vector{Meshes.Vec3}, Vector{Float64}}})
   @ MeshesMakieExt ~/.julia/packages/MakieCore/5nuEY/src/recipes.jl:175
 [9] top-level scope
   @ REPL[5]:1
Some type information was truncated. Use `show(err)` to see complete types.

julia> using GLMakie

julia> ADCSSims.viz(extmesh)
ERROR: No recipe for viz
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] plot!
   @ ~/.julia/packages/Makie/Qvk4f/src/interfaces.jl:227 [inlined]
 [3] connect_plot!(parent::Scene, plot::Plot{Meshes.viz, Tuple{Vector{ADCSSims.ExtendedMesh{…}}}})
   @ Makie ~/.julia/packages/Makie/Qvk4f/src/interfaces.jl:255
 [4] plot!
   @ Makie ~/.julia/packages/Makie/Qvk4f/src/interfaces.jl:260 [inlined]
 [5] plot!(ax::Axis, plot::Plot{Meshes.viz, Tuple{Vector{ADCSSims.ExtendedMesh{Vector{…}, Vector{…}, Vector{…}}}}})
   @ Makie ~/.julia/packages/Makie/Qvk4f/src/figureplotting.jl:291
 [6] plot!(fa::Makie.FigureAxis, plot::Plot{Meshes.viz, Tuple{Vector{ADCSSims.ExtendedMesh{…}}}})
   @ Makie ~/.julia/packages/Makie/Qvk4f/src/figureplotting.jl:288
 [7] _create_plot(F::Function, attributes::Dict{Symbol, Any}, args::Vector{ADCSSims.ExtendedMesh{…}})
   @ Makie ~/.julia/packages/Makie/Qvk4f/src/figureplotting.jl:250
 [8] viz(args::Vector{ADCSSims.ExtendedMesh{Vector{Meshes.Triangle{3, Float64}}, Vector{Meshes.Vec3}, Vector{Float64}}})
   @ MeshesMakieExt ~/.julia/packages/MakieCore/5nuEY/src/recipes.jl:175
 [9] top-level scope
   @ REPL[7]:1
Some type information was truncated. Use `show(err)` to see complete types.
```

2023-12-31 14:45 UTC, xlxs4 commented on src/mesh_preprocessing.jl
> +Meshes.viz(mesh::ExtendedMesh) = Meshes.viz(mesh.mesh)
```
julia> GLMakie.activate!()

julia> ADCSSims.viz(extmesh)
ERROR: No recipe for viz
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] plot!
   @ ~/.julia/packages/Makie/Qvk4f/src/interfaces.jl:227 [inlined]
 [3] connect_plot!(parent::Scene, plot::Plot{Meshes.viz, Tuple{Vector{ADCSSims.ExtendedMesh{…}}}})
   @ Makie ~/.julia/packages/Makie/Qvk4f/src/interfaces.jl:255
 [4] plot!
   @ Makie ~/.julia/packages/Makie/Qvk4f/src/interfaces.jl:260 [inlined]
 [5] plot!(ax::Axis, plot::Plot{Meshes.viz, Tuple{Vector{ADCSSims.ExtendedMesh{Vector{…}, Vector{…}, Vector{…}}}}})
   @ Makie ~/.julia/packages/Makie/Qvk4f/src/figureplotting.jl:291
 [6] plot!(fa::Makie.FigureAxis, plot::Plot{Meshes.viz, Tuple{Vector{ADCSSims.ExtendedMesh{…}}}})
   @ Makie ~/.julia/packages/Makie/Qvk4f/src/figureplotting.jl:288
 [7] _create_plot(F::Function, attributes::Dict{Symbol, Any}, args::Vector{ADCSSims.ExtendedMesh{…}})
   @ Makie ~/.julia/packages/Makie/Qvk4f/src/figureplotting.jl:250
 [8] viz(args::Vector{ADCSSims.ExtendedMesh{Vector{Triangle{3, Float64}}, Vector{Meshes.Vec3}, Vector{Float64}}})
   @ MeshesMakieExt ~/.julia/packages/MakieCore/5nuEY/src/recipes.jl:175
 [9] top-level scope
   @ REPL[18]:1
Some type information was truncated. Use `show(err)` to see complete types.
```

2023-12-31 14:45 UTC, voulgarakisromanos commented on src/mesh_preprocessing.jl
> +Meshes.viz(mesh::ExtendedMesh) = Meshes.viz(mesh.mesh)
try import GLMakie

2023-12-31 17:03 UTC, xlxs4 commented on src/bvh.jl
> +function build_bvh(triangles, depth=0, max_depth=8)
Since `depth` is used internally for recursion, I would make another method and expose that instead:
```julia
build_bvh(triangles; max_depth=8) = _build_bvh(triangles, 0, max_depth)
```
what do you think?

2023-12-31 17:07 UTC, xlxs4 commented on src/bvh.jl
> +using ..ADCSSims: ADCSSims
Is this needed?

2023-12-31 21:51 UTC, xlxs4 commented on src/bvh.jl
> +ray_intersects_polygon(ray::Ray, polygon) = throw("Not implemented yet")
@voulgarakisromanos there's `error` and `throw`. `error` raises an `ErrorException` with a message. `throw` throws an object. That means that `error` will always throw a string (i.e., a message), whereas with `throw` you can throw any object (e.g. an `Int64`)

If you want a generic error (`ErrorException`) with a message, aimed at a user, use `error`. `throw` is typically used to convey more specific information, e.g. `throw(BoundsError(my_array, idx))`. That way you can control the type of the exception, catch it more easily and even control it programmatically in the stack

2023-12-31 21:51 UTC, xlxs4 commented on src/bvh.jl
> +function calculate_aabb(triangles::Vector{Triangle})
This code won't work as intended. For example, if you run `parsefile("afile.ply")` you'll hit the `throw("Not implemented yet")` path instead of calling `calculate_aabb(triangles::Vector{Triangle})`.

Why does that happen? Well, if you `error(typeof(polygons))` you'll see that `polygons` is, indeed, `Vector{Meshes.Triangle{3, Float64}}`. What's the problem?

Could it be an abstract type? That wouldn't make sense, but it's easy to check regardless: `isabstracttype(Meshes.Triangle)` returns `false`.
`fieldtypes` can give you a hint:
```julia
(ADCSSims) julia> fieldtypes(Meshes.Triangle)
(Tuple{Vararg{Meshes.Point{Dim, T}, 3}} where {Dim, T},)
```

From `@edit Meshes.Triangle{3, Float64}([1,2,3])` you can see:

```julia
struct Ngon{N,Dim,T} <: Polygon{Dim,T}
  vertices::NTuple{N,Point{Dim,T}}
end
```

where `Triangle` is just a type alias for `Ngon{3}`.

So you can do
```julia
function calculate_aabb(triangles::Vector{<:Triangle})
```

instead

2023-12-31 21:54 UTC, xlxs4 commented on src/bvh.jl
> +function calculate_aabb(triangles::Vector{Triangle})
@voulgarakisromanos

2023-12-31 21:59 UTC, xlxs4 commented on src/power.jl
> +function calculate_power(
Since you `export` this, it'd be nice if there was a docstring to go along with the method definition

2024-01-01 00:19 UTC, xlxs4 commented on src/bvh.jl
> +    right_polys = filter(t -> centroid(t).coords[axis] > median_val, polygons)
Here you calculate `centroid(t).coords[axis] for t in polygons` three times.
How about:
```julia
    centroids = [Meshes.centroid(t).coords[axis] for t in polygons]
    median_val = median(centroids)
    idx = centroids .<= median_val
    left_polys = polygons[idx]
    right_polys = polygons[.!idx]
```

2024-01-01 21:14 UTC, merged